In [37]:
# Impoerted Library
import pandas as pd

In [118]:
# Load The Dataset
data= pd.read_csv("C:\\Users\\saura\\Downloads\\customer_churn_dataset.csv")
data.head()

,CustomerID,Gender,SeniorCitizen,Tenure,MonthlyCharges,Contract,PaymentMethod,TotalCharges,Churn
0,CUST00000,Male,0,48,106.17,Two year,Credit card,5104.81,Yes
1,CUST00001,Female,0,66,79.03,One year,Bank transfer,5218.59,No
2,CUST00002,Male,0,70,42.63,One year,Mailed check,3010.03,No
3,CUST00003,Male,1,28,58.42,One year,Credit card,1657.03,No
4,CUST00004,Male,0,26,65.01,Month-to-month,Bank transfer,1659.58,Yes

In [202]:
# Drop Unsued Coloumn
data.drop(['CustomerID'],axis=1)
df["Gender"].unique()

array([1, 0])

In [204]:
data["Gender"] = data["Gender"].replace({"Male": 1, "Female": 0})

C:\Users\saura\AppData\Local\Temp\ipykernel_23264\2328369350.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["Gender"] = data["Gender"].replace({"Male": 1, "Female": 0})

In [206]:
#Encoding Churn Data to value of 1 and 0
data['Churn']= data['Churn'].map({'Yes':1,'No':0})

In [208]:
 # Creating Coloumn For the Contract Category
data = pd.get_dummies(data, columns=["Contract"], drop_first=True)

In [210]:
data = pd.get_dummies(data, columns=["PaymentMethod"], drop_first=True)

,CustomerID,Gender,SeniorCitizen,Tenure,MonthlyCharges,TotalCharges,Churn,Contract_One year,Contract_Two year,PaymentMethod_Credit card,PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,CUST00000,1,0,48,106.17,5104.81,1,False,True,True,False,False
1,CUST00001,0,0,66,79.03,5218.59,0,True,False,False,False,False
2,CUST00002,1,0,70,42.63,3010.03,0,True,False,False,False,True
3,CUST00003,1,1,28,58.42,1657.03,0,True,False,True,False,False
4,CUST00004,1,0,26,65.01,1659.58,1,False,False,False,False,False

ValueError: invalid literal for int() with base 10: 'CUST00000'

In [146]:
df.head()

,Gender,SeniorCitizen,Tenure,MonthlyCharges,TotalCharges,Churn,Contract_One year,Contract_Two year,PaymentMethod_Credit card,PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1,0,48,106,5104,1,0,1,1,0,0
1,0,0,66,79,5218,0,1,0,0,0,0
2,1,0,70,42,3010,0,1,0,0,0,1
3,1,1,28,58,1657,0,1,0,1,0,0
4,1,0,26,65,1659,1,0,0,0,0,0

In [164]:
X = df.drop("Churn", axis=1)
y = df["Churn"]

In [166]:
from sklearn.model_selection import train_test_split

In [174]:
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [186]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(max_iter=1000)
model.fit(X_train,Y_train)

LogisticRegression(max_iter=1000)

In [188]:
from sklearn.metrics import classification_report,confusion_matrix
y_pred=model.predict(X_test)
print(classification_report(Y_test,y_pred))
print(confusion_matrix(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.77      0.83      0.80       116
           1       0.73      0.65      0.69        84

    accuracy                           0.76       200
   macro avg       0.75      0.74      0.74       200
weighted avg       0.75      0.76      0.75       200

[[96 20]
 [29 55]]

In [196]:
df["Predicted_Churn"] = model.predict(X)

In [198]:
df["Predicted_Churn"] = df["Predicted_Churn"].map({1: "Yes", 0: "No"})

In [200]:
df.to_csv("churn_with_predictions.csv", index=False)